name: Deploy Web to Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            set -e

            echo "== Masuk ke folder web =="
            cd /var/www/kelompokmjsasep

            echo "== Hapus file lama =="
            sudo rm -rf *

            echo "== Clone repo baru =="
            sudo git clone https://github.com/kadekkrisssna/mjsasep.git .

            echo "== Set permission =="
            sudo chown -R www-data:www-data /var/www/kelompokmjsasep
            sudo chmod -R 755 /var/www/kelompokmjsasep

            echo "== Reload nginx =="
            sudo systemctl reload nginx

            echo "== DEPLOY SELESAI =="
