name: Deploy Web to Nginx

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Deploy files to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.VPS_SECRET_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          rsync -av --delete /github/workspace/ /var/www/kelompokmjsasep/