name: Deploy Web to Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            set -e

            echo "== Pindah ke /var/www =="
            cd /var/www

            echo "== Hapus folder sementara =="
            sudo rm -rf kelompokmjsasep_tmp

            echo "== Clone repo ke folder sementara =="
            sudo git clone https://github.com/kadekkrisssna/mjsasep.git kelompokmjsasep_tmp

            echo "== Kosongkan folder web =="
            sudo rm -rf kelompokmjsasep/*

            echo "== Pindahkan hasil deploy =="
            sudo cp -r kelompokmjsasep_tmp/* kelompokmjsasep/

            echo "== Set permission =="
            sudo chown -R www-data:www-data kelompokmjsasep
            sudo chmod -R 755 kelompokmjsasep

            echo "== Bersihkan =="
            sudo rm -rf kelompokmjsasep_tmp

            echo "== Reload nginx =="
            sudo systemctl reload nginx

            echo "== DEPLOY SELESAI =="
